<a href="https://colab.research.google.com/github/Ziad-Fahmy/Data-Mining/blob/main/01_Numpy_Indexing_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing
* 2) Selection

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr = np.arange(30,40)

In [ ]:
#Show
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

### 1.1) Indexing a 1D array (Vectors)

In [ ]:
#Get a value at an index
arr[8]

38

In [ ]:
#Get values in a range
arr[1:5]

array([31, 32, 33, 34])

In [ ]:
#Get values in a range
arr[0:5]

array([30, 31, 32, 33, 34])

In [ ]:
arr[:5]

array([30, 31, 32, 33, 34])

In [ ]:
arr[3:]

array([33, 34, 35, 36, 37, 38, 39])

In [ ]:
arr[3:7]

array([33, 34, 35, 36])

In [ ]:
arr[3:7:2]

array([33, 35])

In [ ]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
#Setting a value with index range (Broadcasting)
arr[2:5] = 100

#Show
arr

array([ 30,  31, 100, 100, 100,  35,  36,  37,  38,  39])

### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1, 0]

20

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[::-1,::]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [ ]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [ ]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

### 1.3) Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.random.randint(1, 100, (10,10))
arr2d

array([[ 7, 85, 20, 29, 14, 66, 57, 45, 85, 94],
       [44, 51, 95, 36, 48, 87, 94, 44, 25,  5],
       [68,  9, 61, 99, 41, 59, 42, 78, 51, 95],
       [53, 24, 11, 83, 68,  8, 63, 86, 26, 60],
       [54, 13, 42, 83, 62,  1,  7, 77,  5, 59],
       [22, 86, 42, 25,  7, 73, 31, 13, 70, 12],
       [84, 13, 43, 62, 36, 46, 98, 56, 85, 49],
       [23, 69, 99, 11, 25, 97,  6, 18, 10, 74],
       [31,  7, 44, 55, 38, 40,  8, 53, 33, 58],
       [45, 41, 85, 77, 18, 22, 76, 24, 65, 11]])

Fancy indexing allows the following

In [ ]:
arr2d[[1,4,6,8]]

array([[44, 51, 95, 36, 48, 87, 94, 44, 25,  5],
       [54, 13, 42, 83, 62,  1,  7, 77,  5, 59],
       [84, 13, 43, 62, 36, 46, 98, 56, 85, 49],
       [31,  7, 44, 55, 38, 40,  8, 53, 33, 58]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[84, 13, 43, 62, 36, 46, 98, 56, 85, 49],
       [54, 13, 42, 83, 62,  1,  7, 77,  5, 59],
       [68,  9, 61, 99, 41, 59, 42, 78, 51, 95],
       [23, 69, 99, 11, 25, 97,  6, 18, 10, 74]])

In [ ]:
arr2d[[1,4,6,8], 2:5]

array([[95, 36, 48],
       [42, 83, 62],
       [43, 62, 36],
       [44, 55, 38]])

## 2) Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [ ]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])

In [ ]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[arr >= 5]

array([5, 6, 7, 8, 9])

In [ ]:
x = 3
arr[arr > x]

array([4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

# Great Job!
