<a href="https://colab.research.google.com/github/Ziad-Fahmy/Data-Mining/blob/main/02_Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Operations


* 1) Arithmetic and Logic
    - 1.1) Arithmetic
    - 1.2) Logic
* 2) Universal Array Functions
    - 2.1) max, min, average, sum
    - 2.2) power, sqrt, exp, log
    - 2.3) sin, cos, tan
    - 2.4) dot product
* 3) Combine and Split data

## 1) Arithmetic and Logic

You can easily perform array with array arithmetic, or scalar with array arithmetic. <br>
You can also perform logic operation on array. <br>

**Broadcasting**: a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.

Let's see some examples:

### 1.1) Arithmetic

In [ ]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Also warning, but not an error instead infinity
1 / arr

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### 2.2) Logic

In [ ]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

**We can also do operations on 2-D arrays**

In [ ]:
arr = np.random.randint(0,10, (3,3))
arr

array([[1, 1, 1],
       [0, 8, 6],
       [8, 5, 7]])

In [ ]:
arr + 3

array([[ 4,  4,  4],
       [ 3, 11,  9],
       [11,  8, 10]])

In [ ]:
arr - 2

array([[-1, -1, -1],
       [-2,  6,  4],
       [ 6,  3,  5]])

In [ ]:
3 * arr

array([[ 3,  3,  3],
       [ 0, 24, 18],
       [24, 15, 21]])

In [ ]:
arr

array([[1, 1, 1],
       [0, 8, 6],
       [8, 5, 7]])

In [ ]:
arr + 3 * arr

array([[ 4,  4,  4],
       [ 0, 32, 24],
       [32, 20, 28]])

In [ ]:
arr * arr

array([[ 1,  1,  1],
       [ 0, 64, 36],
       [64, 25, 49]])

## 2) Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matrix = np.random.randint(0, 100, (5, 3))
matrix

array([[ 7, 68, 24],
       [ 3, 23, 91],
       [12, 91, 99],
       [36, 75, 68],
       [71, 22, 63]])

### 2.1) max, min, average, sum

**max**

In [ ]:
np.max(arr) #same as arr.max()

9

In [ ]:
np.max(matrix)

92

In [ ]:
np.max(matrix, axis=0)

array([71, 91, 99])

In [ ]:
np.max(matrix, axis=1)

array([68, 91, 99, 75, 71])

**min**

In [ ]:
np.min(arr) #same as arr.min()

0

In [ ]:
np.min(matrix)

20

In [ ]:
np.min(matrix, axis=0)

array([36, 20, 21])

In [ ]:
np.min(matrix, axis=1)

array([20, 38, 39, 26, 32])

**average**

In [ ]:
np.average(arr)

4.5

In [ ]:
np.average(matrix)

46.93333333333333

In [ ]:
np.average(matrix, axis=0)

array([58.6, 41.4, 40.8])

In [ ]:
np.average(matrix, axis=1)

array([32.33333333, 64.66666667, 57.66666667, 29.66666667, 50.33333333])

**sum**

In [ ]:
np.sum(arr)

45

In [ ]:
np.sum(matrix)

704

In [ ]:
np.sum(matrix, axis=0)

array([293, 207, 204])

In [ ]:
np.sum(matrix, axis=1)

array([ 97, 194, 173,  89, 151])

### 2.2) sqrt, exp, log, sin

**power**

In [ ]:
np.power(arr, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [ ]:
np.power(matrix, 3)

array([[175616,   8000,   9261],
       [ 54872, 389017, 571787],
       [778688,  59319,  74088],
       [ 46656,  19683,  17576],
       [357911, 110592,  32768]], dtype=int32)

**sqrt**

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sqrt(matrix)

array([[7.48331477, 4.47213595, 4.58257569],
       [6.164414  , 8.54400375, 9.11043358],
       [9.59166305, 6.244998  , 6.4807407 ],
       [6.        , 5.19615242, 5.09901951],
       [8.42614977, 6.92820323, 5.65685425]])

**exp**

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.exp(matrix)

array([[2.09165950e+24, 4.85165195e+08, 1.31881573e+09],
       [3.18559318e+16, 5.05239363e+31, 1.11286375e+36],
       [9.01762841e+39, 8.65934004e+16, 1.73927494e+18],
       [4.31123155e+15, 5.32048241e+11, 1.95729609e+11],
       [6.83767123e+30, 7.01673591e+20, 7.89629602e+13]])

**log**

In [ ]:
np.log(arr)

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.log(matrix)

array([[4.02535169, 2.99573227, 3.04452244],
       [3.63758616, 4.29045944, 4.41884061],
       [4.52178858, 3.66356165, 3.73766962],
       [3.58351894, 3.29583687, 3.25809654],
       [4.26267988, 3.87120101, 3.4657359 ]])

### 2.3) sin, cos, tan

In [ ]:
angels_arr = np.linspace(0, 360, 9).reshape(3, 3)
angels_arr

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [ ]:
angels_arr = (angels_arr * 2 * np.pi) / 360
angels_arr

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

**sin**

In [ ]:
np.sin(angels_arr)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

**cos**

In [ ]:
np.cos(angels_arr)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

**tan**

In [ ]:
np.tan(angels_arr)

array([[ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16],
       [-1.00000000e+00, -1.22464680e-16,  1.00000000e+00],
       [ 5.44374645e+15, -1.00000000e+00, -2.44929360e-16]])

### 2.4) dot product

In [ ]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])

print(mat)
print()
print(vec1)
print()
print(np.dot(vec1, mat))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[1 2 3]

[24 30 36]


In [ ]:
vec1.dot(mat)

array([24, 30, 36])

## 3) Combine and Split data

* hstack
* vstack
* concatenate
* hsplit
* vsplit

### hstack

In [ ]:
data1 = np.random.randint(5,15,size=(5,3))
data1

array([[12, 10, 14],
       [ 9, 14, 10],
       [11,  8, 11],
       [12, 11,  7],
       [12,  9,  9]])

In [ ]:
data2 = np.random.randint(5,15,size=(5,3))
data2

array([[13,  8, 13],
       [ 6,  5,  8],
       [14, 12,  5],
       [ 8, 11, 13],
       [ 8,  7, 10]])

In [ ]:
np.hstack([data1,data2])

array([[12, 10, 14, 13,  8, 13],
       [ 9, 14, 10,  6,  5,  8],
       [11,  8, 11, 14, 12,  5],
       [12, 11,  7,  8, 11, 13],
       [12,  9,  9,  8,  7, 10]])

### vstack

In [ ]:
np.vstack([data1,data2])

array([[12, 10, 14],
       [ 9, 14, 10],
       [11,  8, 11],
       [12, 11,  7],
       [12,  9,  9],
       [13,  8, 13],
       [ 6,  5,  8],
       [14, 12,  5],
       [ 8, 11, 13],
       [ 8,  7, 10]])

### concatenate

In [ ]:
# stack vertical rows
np.concatenate([data1, data2], axis=0)

array([[12, 10, 14],
       [ 9, 14, 10],
       [11,  8, 11],
       [12, 11,  7],
       [12,  9,  9],
       [13,  8, 13],
       [ 6,  5,  8],
       [14, 12,  5],
       [ 8, 11, 13],
       [ 8,  7, 10]])

In [ ]:
# stack horizontal columns
np.concatenate([data1, data2], axis=1)

array([[12, 10, 14, 13,  8, 13],
       [ 9, 14, 10,  6,  5,  8],
       [11,  8, 11, 14, 12,  5],
       [12, 11,  7,  8, 11, 13],
       [12,  9,  9,  8,  7, 10]])

### hsplit

In [ ]:
stacked_data = np.hstack([data1,data2])
stacked_data

array([[12, 10, 14, 13,  8, 13],
       [ 9, 14, 10,  6,  5,  8],
       [11,  8, 11, 14, 12,  5],
       [12, 11,  7,  8, 11, 13],
       [12,  9,  9,  8,  7, 10]])

In [ ]:
left, right = np.hsplit(stacked_data, 2)

In [ ]:
left

array([[12, 10, 14],
       [ 9, 14, 10],
       [11,  8, 11],
       [12, 11,  7],
       [12,  9,  9]])

In [ ]:
right

array([[13,  8, 13],
       [ 6,  5,  8],
       [14, 12,  5],
       [ 8, 11, 13],
       [ 8,  7, 10]])

### vsplit

In [ ]:
stacked_data = np.vstack([data1,data2])
stacked_data

array([[12, 10, 14],
       [ 9, 14, 10],
       [11,  8, 11],
       [12, 11,  7],
       [12,  9,  9],
       [13,  8, 13],
       [ 6,  5,  8],
       [14, 12,  5],
       [ 8, 11, 13],
       [ 8,  7, 10]])

In [ ]:
up, down = np.vsplit(stacked_data, 2)

In [ ]:
up

array([[12, 10, 14],
       [ 9, 14, 10],
       [11,  8, 11],
       [12, 11,  7],
       [12,  9,  9]])

In [ ]:
down

array([[13,  8, 13],
       [ 6,  5,  8],
       [14, 12,  5],
       [ 8, 11, 13],
       [ 8,  7, 10]])

# Great Job!

That's all we need to know for now!