<a href="https://colab.research.google.com/github/Ziad-Fahmy/Data-Mining/blob/main/numby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Importing numpy library**

In [ ]:
import numpy as np

Creating 2d array

In [ ]:
arr_2d =np.array([[5,10,15],
                  [20,25,30],
                  [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Slicing array to 2*2 array

In [ ]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [ ]:
arr_2d[:, 1:2]

array([[10],
       [25],
       [40]])

In [43]:
arr =np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr + 3



array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [16]:
arr*10


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [17]:
arr -10


array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [22]:
arr / arr


<ipython-input-22-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
1/arr


<ipython-input-21-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [23]:
arr **3


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#Logic

In [24]:
arr > 3


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
arr != 3


array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [27]:
arr = np.random.randint(0,10,(3,3))
arr

array([[2, 6, 6],
       [7, 7, 8],
       [5, 8, 0]])

In [28]:
arr +3

array([[ 5,  9,  9],
       [10, 10, 11],
       [ 8, 11,  3]])

In [29]:
arr * 3

array([[ 6, 18, 18],
       [21, 21, 24],
       [15, 24,  0]])

In [30]:
arr +3 * arr

array([[ 8, 24, 24],
       [28, 28, 32],
       [20, 32,  0]])

##Unifersal array function

In [36]:
matrix =np.random.randint(0,100,(5,3))
matrix

array([[66, 67, 73],
       [59, 76, 49],
       [82, 39, 91],
       [49, 74, 82],
       [19,  8, 90]])

In [32]:
np.max(arr)

98

In [33]:
np.max(arr,axis=0)

array([97, 47, 98])

In [34]:
np.max(arr,axis=1)

array([98, 97, 86, 33,  4])

In [37]:
np.min(matrix,axis=0)

array([19,  8, 49])

In [38]:
np.min(matrix,axis=1)

array([66, 49, 39, 49,  8])

In [39]:
np.max(matrix,axis=0)

array([82, 76, 91])

In [40]:
np.max(matrix,axis=1)

array([73, 76, 91, 82, 90])

In [44]:
np.average(arr)

4.5

In [46]:
np.average(matrix)

61.6

In [47]:
np.sum(arr)

45

In [48]:
np.sum(matrix)

924

In [49]:
np.sum(arr,axis=0)

45

In [51]:
np.sum(matrix,axis=1)

array([206, 184, 212, 205, 117])

In [52]:
np.sum(matrix,axis=0)

array([275, 264, 385])

Power

In [53]:
np.power(arr,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [54]:
np.power(matrix,3)

array([[287496, 300763, 389017],
       [205379, 438976, 117649],
       [551368,  59319, 753571],
       [117649, 405224, 551368],
       [  6859,    512, 729000]])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
np.sqrt(matrix)

array([[8.1240384 , 8.18535277, 8.54400375],
       [7.68114575, 8.71779789, 7.        ],
       [9.05538514, 6.244998  , 9.53939201],
       [7.        , 8.60232527, 9.05538514],
       [4.35889894, 2.82842712, 9.48683298]])

exponential

In [57]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [58]:
np.exp(matrix)

array([[4.60718663e+28, 1.25236317e+29, 5.05239363e+31],
       [4.20121040e+25, 1.01480039e+33, 1.90734657e+21],
       [4.09399696e+35, 8.65934004e+16, 3.31740010e+39],
       [1.90734657e+21, 1.37338298e+32, 4.09399696e+35],
       [1.78482301e+08, 2.98095799e+03, 1.22040329e+39]])

Log()

In [59]:
np.log(arr)

<ipython-input-59-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [60]:
np.log(matrix)

array([[4.18965474, 4.20469262, 4.29045944],
       [4.07753744, 4.33073334, 3.8918203 ],
       [4.40671925, 3.66356165, 4.51085951],
       [3.8918203 , 4.30406509, 4.40671925],
       [2.94443898, 2.07944154, 4.49980967]])

sin, cos, tan

In [61]:
angels_arr = np.linspace(0,360,9).reshape(3,3)
angels_arr

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [62]:
angels_arr = (angels_arr*2*np.pi)/360

angels_arr

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

In [63]:
np.sin(angels_arr)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

In [64]:
np.cos(angels_arr)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

In [65]:
np.tan(angels_arr)

array([[ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16],
       [-1.00000000e+00, -1.22464680e-16,  1.00000000e+00],
       [ 5.44374645e+15, -1.00000000e+00, -2.44929360e-16]])

dot Product

In [68]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])

print(mat)
print()
print(vec1)
print()
print(np.dot(mat,vec1)) #dot product

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[1 2 3]

[ 8 26 44]


###combine and split data

hstack

In [69]:
data1 = np.random.randint(5,15,size=(5,3))
data1

array([[ 6, 13,  8],
       [14,  6,  8],
       [10, 13, 11],
       [12,  8,  6],
       [ 6,  5,  5]])

In [70]:
data2 = np.random.randint(5,15,size=(5,3))
data2

array([[12, 14, 10],
       [ 9,  9,  8],
       [12,  5,  9],
       [ 9,  7,  8],
       [13,  5,  9]])

In [71]:
np.hstack((data1,data2))   #make two matrices together in matrix h axis

array([[ 6, 13,  8, 12, 14, 10],
       [14,  6,  8,  9,  9,  8],
       [10, 13, 11, 12,  5,  9],
       [12,  8,  6,  9,  7,  8],
       [ 6,  5,  5, 13,  5,  9]])

In [72]:
np.vstack((data1,data2))  #make two matrices together in matrix y axis

array([[ 6, 13,  8],
       [14,  6,  8],
       [10, 13, 11],
       [12,  8,  6],
       [ 6,  5,  5],
       [12, 14, 10],
       [ 9,  9,  8],
       [12,  5,  9],
       [ 9,  7,  8],
       [13,  5,  9]])

In [73]:
np.concatenate((data1,data2),axis=0)

array([[ 6, 13,  8],
       [14,  6,  8],
       [10, 13, 11],
       [12,  8,  6],
       [ 6,  5,  5],
       [12, 14, 10],
       [ 9,  9,  8],
       [12,  5,  9],
       [ 9,  7,  8],
       [13,  5,  9]])

In [80]:
stcked_data = np.concatenate((data1,data2),axis=1)

In [81]:
left, right =np.hsplit(stcked_data,2)
print(left)
print()
print(right)

[[ 6 13  8]
 [14  6  8]
 [10 13 11]
 [12  8  6]
 [ 6  5  5]]

[[12 14 10]
 [ 9  9  8]
 [12  5  9]
 [ 9  7  8]
 [13  5  9]]


In [82]:
v_stacked_data = np.vstack((data1,data2))

In [85]:
up, down = np.vsplit(v_stacked_data,2)
print(up)
print()


[[ 6 13  8]
 [14  6  8]
 [10 13 11]
 [12  8  6]
 [ 6  5  5]]



In [84]:
print(down)

[[12 14 10]
 [ 9  9  8]
 [12  5  9]
 [ 9  7  8]
 [13  5  9]]
